# Generated by Django 3.0.2 on 2020-01-22 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(verbose_name='date admissioned')),
                ('name', models.CharField(max_length=30)),
                ('bed_number', models.CharField(max_length=30)),
                ('chart_id', models.CharField(max_length=30)),
                ('age', models.PositiveSmallIntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=1)),
                ('diagnosis', models.CharField(max_length=100)),
                ('secondary_diagnosis', models.CharField(max_length=100)),
                ('progress_note', models.TextField()),
                ('admission_note', models.TextField()),
                ('discharge_note', models.TextField()),
                ('weekly_summary', models.TextField()),
                ('discharged', models.BooleanField()),
                ('memo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField()),
                ('alert_time', models.DateTimeField()),
                ('done', models.BooleanField()),
                ('priority', models.PositiveSmallIntegerField()),
                ('color', models.CharField(max_length=30)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.Admission')),
            ],
        ),
    ]
