# Generated by Django 3.0.2 on 2020-01-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admission_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='diagnosis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='admission',
            name='discharge_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='memo',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='progress_note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='secondary_diagnosis',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='admission',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=1),
        ),
        migrations.AlterField(
            model_name='admission',
            name='weekly_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='alert_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='color',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='item',
            name='priority',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='stop_time',
            field=models.DateTimeField(blank=True),
        ),
    ]
