# Generated by Django 3.0.2 on 2020-01-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_auto_20200122_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='alert_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='stop_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
